### ISSUE TITLE
Strict Coverage does not work properly with PHPDBG

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#361]
The following examples use the https://github.com/sebastianbergmann/money/ repository.

## PHPDBG (PHP 7.0; https://github.com/php/php-src/commit/4cf9011c626e8920beed95bab49284de13dc4459)

```
$ phpdbg -rr ../phpunit/phpunit -c build
[Welcome to phpdbg, the interactive PHP debugger, v0.5.0]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
#!/usr/bin/env php
PHPUnit 5.0-gb302a44 by Sebastian Bergmann and contributors.

Runtime:	PHPDBG 7.0.0-dev
Configuration:	/usr/local/src/money/build/phpunit.xml

RRRRRSSSSSSRRRRRRRRSRSRRRRRRRRRRRRRRRSSSSSRR

Time: 533 ms, Memory: 14.00Mb

There were 31 risky tests:

1) SebastianBergmann\Money\CurrencyTest::testExceptionIsRaisedForInvalidConstructorArgument
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0

2) SebastianBergmann\Money\CurrencyTest::testCanBeConstructedFromUppercaseString
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0

3) SebastianBergmann\Money\CurrencyTest::testCanBeConstructedFromLowercaseString
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0

4) SebastianBergmann\Money\CurrencyTest::testCustomCurrencyCanBeRegistered
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0

5) SebastianBergmann\Money\CurrencyTest::testRegisteredCurrenciesCanBeAccessed
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:1137
- /usr/local/src/money/src/Currency.php:1138
- /usr/local/src/money/src/Currency.php:1141
- /usr/local/src/money/src/Currency.php:1142
- /usr/local/src/money/src/Currency.php:1143
- /usr/local/src/money/src/Currency.php:0

6) SebastianBergmann\Money\IntlFormatterTest::testMoneyObjectCanBeFormattedAsString
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0

7) SebastianBergmann\Money\MoneyTest::testCannotBeConstructedFromNonIntegerValue
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144
- /usr/local/src/money/src/Money.php:465
- /usr/local/src/money/src/Money.php:469
- /usr/local/src/money/src/Money.php:473
- /usr/local/src/money/src/Money.php:0

8) SebastianBergmann\Money\MoneyTest::testCannotBeConstructedUsingInvalidCurrencyArgument
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144
- /usr/local/src/money/src/Money.php:0

9) SebastianBergmann\Money\MoneyTest::testCannotBeConstructedUsingInvalidValueArgument
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:54
- /usr/local/src/money/src/Money.php:58
- /usr/local/src/money/src/Money.php:59
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144
- /usr/local/src/money/src/Money.php:465
- /usr/local/src/money/src/Money.php:469
- /usr/local/src/money/src/Money.php:473
- /usr/local/src/money/src/Money.php:0

10) SebastianBergmann\Money\MoneyTest::testObjectCanBeConstructedFromIntegerValueAndCurrencyObject
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144

11) SebastianBergmann\Money\MoneyTest::testObjectCanBeConstructedFromIntegerValueAndCurrencyString
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144

12) SebastianBergmann\Money\MoneyTest::testObjectCanBeConstructedFromStringValueAndCurrencyObject
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144

13) SebastianBergmann\Money\MoneyTest::testObjectCanBeConstructedFromStringValueAndCurrencyString
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144

14) SebastianBergmann\Money\MoneyTest::testConvertedAmountCanBeRetrieved
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:144

15) SebastianBergmann\Money\MoneyTest::testAnotherMoneyObjectWithSameCurrencyCanBeAdded
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133

16) SebastianBergmann\Money\MoneyTest::testExceptionIsThrownForOverflowingAddition
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:0

17) SebastianBergmann\Money\MoneyTest::testExceptionIsRaisedForIntegerOverflow
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144
- /usr/local/src/money/src/Money.php:0

18) SebastianBergmann\Money\MoneyTest::testExceptionIsRaisedWhenMoneyObjectWithDifferentCurrencyIsAdded
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:0

19) SebastianBergmann\Money\MoneyTest::testAnotherMoneyObjectWithSameCurrencyCanBeSubtracted
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133

20) SebastianBergmann\Money\MoneyTest::testExceptionIsThrownForOverflowingSubtraction
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:0

21) SebastianBergmann\Money\MoneyTest::testExceptionIsRaisedWhenMoneyObjectWithDifferentCurrencyIsSubtracted
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:0

22) SebastianBergmann\Money\MoneyTest::testCanBeNegated
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144

23) SebastianBergmann\Money\MoneyTest::testCanBeMultipliedByAFactor
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144

24) SebastianBergmann\Money\MoneyTest::testExceptionIsRaisedWhenMultipliedUsingInvalidRoundingMode
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144
- /usr/local/src/money/src/Money.php:0

25) SebastianBergmann\Money\MoneyTest::testCanBeAllocatedToNumberOfTargets
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144

26) SebastianBergmann\Money\MoneyTest::testPercentageCanBeExtracted
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133

27) SebastianBergmann\Money\MoneyTest::testExceptionIsRaisedWhenTryingToAllocateToInvalidNumberOfTargets
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144
- /usr/local/src/money/src/Money.php:0

28) SebastianBergmann\Money\MoneyTest::testCanBeAllocatedByRatios
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:144

29) SebastianBergmann\Money\MoneyTest::testCanBeComparedToAnotherMoneyObjectWithSameCurrency
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133

30) SebastianBergmann\Money\MoneyTest::testExceptionIsRaisedWhenComparedToMoneyObjectWithDifferentCurrency
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63
- /usr/local/src/money/src/Money.php:133
- /usr/local/src/money/src/Money.php:0

31) SebastianBergmann\Money\MoneyTest::testCanBeSerializedToJson
This test executed code that is not listed as code to be covered or used:
- /usr/local/src/money/src/Currency.php:0
- /usr/local/src/money/src/IntlFormatter.php:37
- /usr/local/src/money/src/IntlFormatter.php:38
- /usr/local/src/money/src/IntlFormatter.php:40
- /usr/local/src/money/src/IntlFormatter.php:50
- /usr/local/src/money/src/IntlFormatter.php:61
- /usr/local/src/money/src/IntlFormatter.php:62
- /usr/local/src/money/src/IntlFormatter.php:63

--

There were 13 skipped tests:

1) SebastianBergmann\Money\CurrencyTest::testCanBeCastToString
This test depends on &quot;SebastianBergmann\Money\CurrencyTest::testCanBeConstructedFromUppercaseString&quot; to pass.

2) SebastianBergmann\Money\CurrencyTest::testCurrencyCodeCanBeRetrieved
This test depends on &quot;SebastianBergmann\Money\CurrencyTest::testCanBeConstructedFromUppercaseString&quot; to pass.

3) SebastianBergmann\Money\CurrencyTest::testDefaultFractionDigitsCanBeRetrieved
This test depends on &quot;SebastianBergmann\Money\CurrencyTest::testCanBeConstructedFromUppercaseString&quot; to pass.

4) SebastianBergmann\Money\CurrencyTest::testDisplayNameCanBeRetrieved
This test depends on &quot;SebastianBergmann\Money\CurrencyTest::testCanBeConstructedFromUppercaseString&quot; to pass.

5) SebastianBergmann\Money\CurrencyTest::testNumericCodeCanBeRetrieved
This test depends on &quot;SebastianBergmann\Money\CurrencyTest::testCanBeConstructedFromUppercaseString&quot; to pass.

6) SebastianBergmann\Money\CurrencyTest::testSubUnitCanBeRetrieved
This test depends on &quot;SebastianBergmann\Money\CurrencyTest::testCanBeConstructedFromUppercaseString&quot; to pass.

7) SebastianBergmann\Money\MoneyTest::testAmountCanBeRetrieved
This test depends on &quot;SebastianBergmann\Money\MoneyTest::testObjectCanBeConstructedFromIntegerValueAndCurrencyObject&quot; to pass.

8) SebastianBergmann\Money\MoneyTest::testCurrencyCanBeRetrieved
This test depends on &quot;SebastianBergmann\Money\MoneyTest::testObjectCanBeConstructedFromIntegerValueAndCurrencyObject&quot; to pass.

9) SebastianBergmann\Money\MoneyTest::testCanBeComparedToAnotherMoneyObjectWithSameCurrency2
This test depends on &quot;SebastianBergmann\Money\MoneyTest::testCanBeComparedToAnotherMoneyObjectWithSameCurrency&quot; to pass.

10) SebastianBergmann\Money\MoneyTest::testCanBeComparedToAnotherMoneyObjectWithSameCurrency3
This test depends on &quot;SebastianBergmann\Money\MoneyTest::testCanBeComparedToAnotherMoneyObjectWithSameCurrency&quot; to pass.

11) SebastianBergmann\Money\MoneyTest::testCanBeComparedToAnotherMoneyObjectWithSameCurrency4
This test depends on &quot;SebastianBergmann\Money\MoneyTest::testCanBeComparedToAnotherMoneyObjectWithSameCurrency&quot; to pass.

12) SebastianBergmann\Money\MoneyTest::testCanBeComparedToAnotherMoneyObjectWithSameCurrency5
This test depends on &quot;SebastianBergmann\Money\MoneyTest::testCanBeComparedToAnotherMoneyObjectWithSameCurrency&quot; to pass.

13) SebastianBergmann\Money\MoneyTest::testCanBeComparedToAnotherMoneyObjectWithSameCurrency6
This test depends on &quot;SebastianBergmann\Money\MoneyTest::testCanBeComparedToAnotherMoneyObjectWithSameCurrency&quot; to pass.

OK, but incomplete, skipped, or risky tests!
Tests: 31, Assertions: 46, Skipped: 13, Risky: 31.

Generating code coverage report in Clover XML format ... done

Generating Crap4J report XML file ... done

Generating code coverage report in HTML format ... done

Generating code coverage report in PHPUnit XML format ... done
```

## PHP 5.6.11 with Xdebug 2.3.3

```
$ phpunit -c build
PHPUnit 5.0-gb302a44 by Sebastian Bergmann and contributors.

Runtime:	PHP 5.6.11 with Xdebug 2.3.3
Configuration:	/usr/local/src/money/build/phpunit.xml

............................................

Time: 735 ms, Memory: 13.25Mb

OK (44 tests, 70 assertions)

Generating code coverage report in Clover XML format ... done

Generating Crap4J report XML file ... done

Generating code coverage report in HTML format ... done

Generating code coverage report in PHPUnit XML format ... done
```

**Comment by sebastianbergmann** [comment]
@staabm @bwoebi This one's for you :-)

**Comment by bwoebi** [comment]
To remove these on line 0, add a `if (isset($sourceLines[$file][$lineNo]))` branch to `PHP_CodeCoverage_Driver_PHPDBG::detectExecutedLines()`, I'd say. Is it that your issue?

**Comment by staabm** [comment]
I will check chat.

**Comment by staabm** [comment]
@bwoebi the change you suggested doesnt solve the problem.

the error with `/usr/local/src/money/src/Currency.php:0` happens, because phpdbg reports the line 0 as covered by the class.

Not sure we should drop this value in the PHPUnit PHPDBG driver or in PHPDBG itself...?

I am debugging the other findings right now..

**Comment by bwoebi** [comment]
@staabm It reports line 0 when it finds for example exceptions. `phpdbg_end_oplog()` finds _every_ executed opcode. `phpdbg_get_executable()` finds only actually meaningful opcodes [like it exempts NOP's, opcodes to receive ops etc.]. Hence you need to add that branch.

Are you sure that both fixes combined don't solve the problem?

The only one left is then
```
This test executed code that is not listed as code to be covered or used:
- /Users/Bob/money/src/Money.php:473
```
which looks very much like a false positive? (The bug should be somewhere else here)

**Comment by staabm** [comment]
@bwoebi you are right. when both patches are combined, it looks better. PR incoming.

**Comment by bwoebi** [comment]
So, is this one fixed now? Or still any issues?

**Comment by staabm** [comment]
as always, we still have problems with the money ;-)

```
This test executed code that is not listed as code to be covered or used:
- /Users/Bob/money/src/Money.php:473
```

requires some investigation..

**Comment by bwoebi** [comment]
But that looks rather like a failure otherwhere (unrelated to phpdbg driver?)??

**Comment by staabm** [comment]
At least with the xdebug driver it works.. :-)

Will investigate...

**Comment by bwoebi** [comment]
Yeah. But that's because the final ZEND_VERIFY_ABSTRACT_CLASS opcode has an other line number than in 5.6.

In PHP 7, that opcodes line number collides with the final return of the last method, which is why we get a failure here. I need to fix that in compiler in php-src.

**Comment by bwoebi** [comment]
@staabm @sebastianbergmann fixed in php-src. Should work as expected now.
