### ISSUE TITLE
Anon classes are not properly recognized

### ISSUE THREAD

**Issue by kelunik** [sebastianbergmann/php-code-coverage#373]
Anon classes break code coverage, because `new class extends ...` is interpreted as `class extends`, so as a completely new class.

**Comment by sebastianbergmann** [comment]
Will you be working on this?

**Comment by kelunik** [comment]
Not during the next two weeks, but maybe @bwoebi, @staabm or @rdlowrey will.

**Comment by sebastianbergmann** [comment]
I might be able to work on this next week. Just wanted to avoid duplicated work.

**Comment by sebastianbergmann** [comment]
Might just be fixed by https://github.com/sebastianbergmann/php-token-stream/commit/3ab72c62e550370a6cd5dc873e1a04ab57562f5b

**Comment by kelunik** [comment]
Nope, it's not fixed yet. I just pushed my testing repository: https://github.com/kelunik/php-anon-class-coverage

```
phpdbg -qrr vendor/bin/phpunit --coverage-html=coverage/
```

`baz` is shown as outside of `Test` and doesn't have executable lines.

**Comment by sebastianbergmann** [comment]
@kelunik You're right; https://github.com/sebastianbergmann/php-token-stream/issues/52 needs to be fixed, too.

**Comment by sebastianbergmann** [comment]
With https://github.com/sebastianbergmann/php-token-stream/issues/52 fixed this, too, looks fixed to me.

**Comment by sebastianbergmann** [comment]
@kelunik Can you please verify that this has been fixed? Thanks!

**Comment by kelunik** [comment]
@sebastianbergmann As mentioned in http://chat.stackoverflow.com/transcript/message/25887712#25887712, it's still missing a classname in the first column.

**Comment by sebastianbergmann** [comment]
Hm. To me, anonymous classes and functions are private implementation details of the function or method that declares and uses them. They should not show up in the list at all.

**Comment by sebastianbergmann** [comment]
![screenshot from 2015-09-23 17-05-45](https://cloud.githubusercontent.com/assets/25218/10048910/6d022e0e-6215-11e5-97e3-d67ba33eb507.png)

**Comment by sebastianbergmann** [comment]
This looks correct to me (apart from the fact that the executable lines of the anonymous class are not highlighted, maybe this is a bug in PHPDBG?).

**Comment by bwoebi** [comment]
Should be correct in PHPDBG, at least I tried just a simple anon class and the lines were indicated as run and executable.

**Comment by sebastianbergmann** [comment]
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by kelunik** [comment]
Will do if I notice further issues. A lot changed in the last two years. :+1:
